env: 
  global: 
  - secure: "V0ZyyJimvA47fZYclB7QfHzZdrIyjADIUGrucDI6M6/UgR7bWyLcRAgMUl5SejEjSJbuY7AtHfHZs1qFm6Kiro/weWjo8OyClHyPVISl4r1ZjvKL/SQz7B4KIn4NEvopqfk6QSX43RF/IOXjCgLdiaPMFi+2uHgSWNoJ9EHXJSc="
language: java
script: mvn test
